---
root: true

parser: babel-eslint

extends: eslint-config-airbnb

plugins:
  - react

env:
  browser: true
  node: true

rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  import/no-extraneous-dependencies: [2, {"devDependencies": true}]
  id-length: [2, {"exceptions": ["e", "i", "_", "t", "R"]}]
  semi: [2, "never"]
  no-mixed-operators: 0
  no-nested-ternary: 0
  jsx-quotes: [2, "prefer-double"]
  max-len: 1
