version: '3'
services:
  nginx:
    build:
      context: ./nginx
    links:
        - node1:node1
    ports:
        - "49160:80"
  node1:
    build:
      context: ./
    links:
        - redis
    ports:
        - "4000"
  redis:
    image: redis:4-alpine
    ports:
        - "6379"
